name: Publish Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  win-build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Pack into zip and create installer
      run: npm run dist-win
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: artifact-win
        path: dist
  mac-build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Pack into zip and create installer
      run: npm run pack-mac
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: artifact-mac
        path: dist
